services:
  repo1:
    - service1
    - service2
  repo2:
    - service3
    - service4
dbs:
  repo1:
    service1: repo1/service1/dump.sql
    service2: repo1/service2/dump.sql
  repo2:
    service1: repo2/service1/dump.sql
    service2: repo2/service2/dump.sql
models:
  repo1:
    User: users
    UserAccount: user_accounts
targets:
  repo1:
    User: &repo1_target_services
      - service1
      - service2
    UserAccount: <<: *repo1_target_services
  repo2:
    - User
