suppliers:
  domain1:
    - supplier1
    - supplier2
  domain2:
    - supplier3
    - supplier4
dbs:
  domain1/supplier1: domain1/supplier1/dump.sql
  domain1/supplier2: domain1/supplier2/dump.sql
  domain2/supplier1: domain2/supplier1/dump.sql
  domain2/supplier2: domain2/supplier2/dump.sql
models:
  domain1:
    User: users
    UserAccount: user_accounts
